### ISSUE TITLE
Bump Eirinifs to latest

### ISSUE THREAD

**Issue by madamkiwi** [cloudfoundry-community/eirini-bosh-release#27]
Hi @viovanov and team,

We would like to get an eirini-bosh-release version that has an eirinifs blob with a cflinuxfs3 Digest in the release notes (currently the minimum version of eirinifs that has this is 52.0.0).  Can you please bump the eirinifs blob?

Thanks!
@jpalermo && @madamkiwi

**Comment by mudler** [comment]
Closing this as the PR was merged. Thank you :)
