### ISSUE TITLE
Bump eirinifs blob 

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry-community/eirini-bosh-release#4]
Hi @viovanov and others!

A new release of eirinifs that uses `cflinuxfs3` instead of `cflinuxfs2` was just made available: https://github.com/cloudfoundry-incubator/eirinifs/releases/tag/v34.0.0

Is there a pipeline to automatically pull new releases of `eirinifs` and create a new blob or is this done by hand? If it's automatic, feel free to close this issue. If it's done by hand, than this is a request to update that blob :)

Thanks!
Jen + @jspawar

**Comment by viovanov** [comment]
#6 bumps eirinifs and eirini itself
right now this is automatic 
@jenspinney please close this if it's what you needed
